
import { useMemo, useState, useRef } from 'react';
import { Search, Command, ChevronDown, Layers3, Network, Zap, Building2, Factory, Eye, SlidersHorizontal, Plus, Minus, LocateFixed, Orbit, Compass, PanelRightClose, ArrowUpRight, BookOpen, Sparkles, Clock3, GitBranch, X, Moon, Sun, GraduationCap } from 'lucide-react';

const nodes = [
  { id:'root', title:'Decreto 5.163', short:'Regulamentação da comercialização de energia elétrica', kind:'norma', layer:'institucional', env:'NEUTRO', level:0, x:50,y:46,z:0, complexity:2, article:'Decreto nº 5.163, de 30 de julho de 2004', summary:'Regulamenta a comercialização de energia elétrica, o processo de outorga de concessões e de autorizações de geração de energia elétrica.' },
  { id:'instituicoes',title:'Instituições do setor',short:'Papéis e competências',kind:'conceito',layer:'institucional',env:'NEUTRO',level:1,x:50,y:20,z:-55,complexity:2,article:'Capítulo I',summary:'Conheça os agentes institucionais e suas atribuições na organização do setor elétrico.'},
  { id:'comercializacao',title:'Comercialização',short:'Contratação de energia',kind:'conceito',layer:'contratual',env:'AMBOS',level:1,x:25,y:43,z:-55,complexity:4,article:'Capítulo II · Art. 1º',summary:'O decreto organiza a comercialização de energia elétrica entre os ambientes de contratação regulada e livre.'},
  { id:'acl',title:'Ambiente livre · ACL',short:'Negociação bilateral',kind:'conceito',layer:'contratual',env:'ACL',level:2,x:15,y:70,z:-105,complexity:3,article:'Capítulo II · Arts. 47 a 52',summary:'No Ambiente de Contratação Livre, as operações de compra e venda são pactuadas por meio de contratos bilaterais.'},
  { id:'acr',title:'Ambiente regulado · ACR',short:'Leilões e contratos',kind:'conceito',layer:'contratual',env:'ACR',level:2,x:38,y:71,z:-105,complexity:4,article:'Capítulo II · Arts. 11 a 46',summary:'No Ambiente de Contratação Regulada, a compra e venda de energia é realizada por meio de licitações e contratos regulados.'},
  { id:'lastro',title:'Lastro e garantia física',short:'Segurança do suprimento',kind:'conceito',layer:'institucional',env:'AMBOS',level:2,x:72,y:34,z:-105,complexity:5,article:'Capítulo II · Art. 2º',summary:'A contratação deve observar a cobertura do consumo e as regras de lastro previstas no decreto e em regulamentação aplicável.'},
  { id:'leiloes',title:'Leilões de energia',short:'A-1 · A-3 · A-5',kind:'timeline',layer:'leiloes',env:'ACR',level:3,x:35,y:89,z:-155,complexity:3,article:'',summary:'Os leilões organizam a contratação regulada e consideram diferentes prazos de entrega e produtos.'},
  { id:'penalidades',title:'Penalidades',short:'Consequências e sanções',kind:'conceito',layer:'penalidades',env:'AMBOS',level:2,x:84,y:65,z:-105,complexity:3,article:'Capítulo III',summary:'O decreto prevê consequências regulatórias para o descumprimento de obrigações de comercialização.'},
  { id:'quiz',title:'Posso migrar para o ACL?',short:'Decisão interativa',kind:'quiz',layer:'contratual',env:'ACL',level:3,x:7,y:91,z:-155,complexity:2,article:'Consulte a legislação vigente',summary:'A elegibilidade para o mercado livre depende da legislação e regulamentação vigentes. Use esta trilha como orientação de estudo.'},
];
const edges = [['root','instituicoes'],['root','comercializacao'],['root','lastro'],['root','penalidades'],['comercializacao','acl'],['comercializacao','acr'],['acr','leiloes'],['acl','quiz'],['lastro','penalidades']];
const layerLabels = {institucional:'Institucional',contratual:'Contratual',penalidades:'Penalidades',leiloes:'Leilões'};
const personas = [{id:'todos',label:'Todos',icon:Eye},{id:'gerador',label:'Gerador',icon:Zap},{id:'distribuidor',label:'Distribuidor',icon:Building2},{id:'consumidor',label:'Consumidor livre',icon:Factory}];
const nodeInsights = {
  root:'O decreto estrutura a comercialização de energia e trata de concessões e autorizações de geração. Consulte sempre a versão consolidada e as normas posteriores relacionadas.',
  instituicoes:'A regulação distribui responsabilidades entre órgãos e agentes do setor. ANEEL regula e fiscaliza; CCEE viabiliza a contabilização e liquidação das operações; ONS coordena a operação do sistema.',
  comercializacao:'A organização se divide entre contratação regulada e livre. Contratos, contabilização e obrigações de cobertura conectam os agentes aos dois ambientes.',
  acl:'No ACL, compradores e vendedores negociam condições bilateralmente. A representação, o registro contratual e as regras de participação seguem a regulamentação vigente.',
  acr:'No ACR, distribuidoras contratam energia por mecanismos regulados, incluindo leilões. Os contratos resultantes seguem condições e prazos definidos para cada produto.',
  lastro:'A contratação deve guardar relação com a cobertura do consumo e com os requisitos de lastro. As regras de verificação e penalidade também dependem de normas complementares.',
  leiloes:'Os rótulos A-1, A-3 e A-5 indicam, conceitualmente, anos de antecedência em relação ao início do fornecimento. Produtos, calendários e condições variam conforme cada certame.',
  penalidades:'O descumprimento de obrigações pode gerar consequências regulatórias e comerciais. A apuração considera as regras aplicáveis ao agente, ao contrato e ao período.',
  quiz:'A elegibilidade ao ACL depende dos requisitos legais e regulatórios atuais. Use a pergunta como ponto de partida e confirme os critérios vigentes antes de tomar decisões.'
};

export default function App(){
  const [mode,setMode]=useState('2D'); const [selected,setSelected]=useState('comercializacao'); const [query,setQuery]=useState(''); const [persona,setPersona]=useState('todos'); const [activeLayers,setActiveLayers]=useState(['institucional','contratual','leiloes']); const [drawer,setDrawer]=useState(true); const [zoom,setZoom]=useState(1); const [toast,setToast]=useState('');
  const [dark,setDark]=useState(()=>localStorage.getItem('mapa-theme')==='dark');
  const [camera,setCamera]=useState({x:17,y:-20,panX:0,panY:0,zoom:1});
  const drag=useRef(null);
  const focusOrigin=useRef(null);
  const [focusedNode,setFocusedNode]=useState(null);
  const [focusOffset,setFocusOffset]=useState({x:0,y:0,scale:1});
  const resetCamera=()=>setCamera({x:17,y:-20,panX:0,panY:0,zoom:1});
  const onPointerDown=(e)=>{if(mode!=='3D'||e.target.closest('button'))return;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,panX:camera.panX,panY:camera.panY,rotX:camera.x,rotY:camera.y,button:e.button};e.currentTarget.setPointerCapture(e.pointerId)};
  const onPointerMove=(e)=>{if(!drag.current||drag.current.id!==e.pointerId)return;const d=drag.current;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(d.button===2||e.shiftKey)setCamera(c=>({...c,panX:d.panX+dx,panY:d.panY+dy}));else setCamera(c=>({...c,y:d.rotY+dx*.45,x:Math.max(-5,Math.min(75,d.rotX-dy*.35))}))};
  const onPointerUp=(e)=>{if(drag.current?.id===e.pointerId)drag.current=null};
  const onWheel=(e)=>{if(mode!=='3D')return;e.preventDefault();setCamera(c=>({...c,zoom:Math.max(.55,Math.min(2.2,c.zoom*(e.deltaY<0?1.08:.92)))}))};
  const toggleNodeFocus=(e,node)=>{
    e.stopPropagation();
    if(focusedNode===node.id){if(focusOrigin.current?.mode==='3D')setCamera(focusOrigin.current.camera);setFocusedNode(null);setFocusOffset({x:0,y:0,scale:1});focusOrigin.current=null;return}
    if(!focusOrigin.current)focusOrigin.current={mode,camera:{...camera},zoom};
    const stage=e.currentTarget.closest('.map-stage'),stageRect=stage.getBoundingClientRect();
    if(mode==='3D'){
      const nodeRect=e.currentTarget.getBoundingClientRect();
      const original=focusOrigin.current.camera;
      const factor=targetZoom/camera.zoom;
      setCamera(c=>({...c,zoom:targetZoom,panX:c.panX+(stageRect.left+stageRect.width/2-nodeRect.left-nodeRect.width/2)*factor,panY:c.panY+(stageRect.top+stageRect.height/2-nodeRect.top-nodeRect.height/2)*factor}));
    }else{
      const scale=zoom*1.65;
      setFocusOffset({x:(.5-node.x/100)*stageRect.width*scale,y:(.5-node.y/100)*stageRect.height*scale,scale});
    }
    setFocusedNode(node.id);
  };
  const toggleTheme=()=>setDark(v=>{localStorage.setItem('mapa-theme',v?'light':'dark');return !v});
  const changeMode=next=>{if(focusOrigin.current?.mode==='3D')setCamera(focusOrigin.current.camera);focusOrigin.current=null;setFocusedNode(null);setFocusOffset({x:0,y:0,scale:1});setMode(next)};
  const filtered=useMemo(()=>nodes.filter(n=>n.title.toLowerCase().includes(query.toLowerCase())||n.short.toLowerCase().includes(query.toLowerCase())),[query]);
  const visible=(n)=>activeLayers.includes(n.layer)||n.id==='root';
  const pick=(id)=>{setSelected(id);setDrawer(true)};
  const toggleLayer=(id)=>setActiveLayers(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  const current=nodes.find(n=>n.id===selected)||nodes[0];
  const backFacing=mode==='3D'&&Math.cos(camera.x*Math.PI/180)*Math.cos(camera.y*Math.PI/180)<0;
  return <main className={`app-shell ${dark?'dark':''}`}>
    <header className="topbar">
      <label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque um conceito, artigo ou tema…"/><kbd><Command size={11}/> K</kbd></label>
      <div className="top-actions"><button className="persona-select"><span className="avatar"><Eye size={14}/></span>{personas.find(p=>p.id===persona)?.label}<ChevronDown size={14}/><select aria-label="Selecionar persona" value={persona} onChange={e=>setPersona(e.target.value)}>{personas.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></button><div className="mode-switch"><button className={mode==='2D'?'active':''} onClick={()=>changeMode('2D')}><Network size={15}/> 2D</button><button className={mode==='3D'?'active':''} onClick={()=>changeMode('3D')}><Orbit size={15}/> 3D</button></div><button className="icon-button" title={dark?'Ativar tema claro':'Ativar tema escuro'} aria-label={dark?'Ativar tema claro':'Ativar tema escuro'} onClick={toggleTheme}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button></div>
    </header>
    <div className="workspace">
      <aside className="layer-panel"><div className="panel-heading"><span>EXPLORAR</span><button className="quiet-button"><SlidersHorizontal size={15}/></button></div><div className="panel-section"><p className="section-label">CAMADAS</p>{Object.entries(layerLabels).map(([id,label])=><label className="layer-row" key={id}><input type="checkbox" checked={activeLayers.includes(id)} onChange={()=>toggleLayer(id)}/><span className={`layer-dot ${id}`}/><span>{label}</span><small>{nodes.filter(n=>n.layer===id).length}</small></label>)}</div><div className="panel-section persona-list"><p className="section-label">VER COMO</p>{personas.map(({id,label,icon:Icon})=><button key={id} className={`persona-row ${persona===id?'chosen':''}`} onClick={()=>setPersona(id)}><Icon size={15}/>{label}{persona===id&&<span className="selected-dot"/>}</button>)}</div><div className="legend"><p className="section-label">LEGENDA</p><div><i className="legend-node"/> Conceito</div><div><i className="legend-ring"/> Decisão interativa</div><div><i className="legend-line"/> Relação no decreto</div></div><div className="sidebar-foot"><span className="live-dot"/> Conteúdo em desenvolvimento</div></aside>
      <section className={`canvas-area ${mode==='3D'?'scene-3d':''}`} aria-label={`Mapa regulatório em ${mode}`}>
        <div className="canvas-toolbar"><div className="crumb"><span>Mapa mental</span><span className="crumb-sep">/</span><strong>{mode} · Visão geral</strong></div><div className="canvas-tools">{mode==='3D'?<><button className="square-tool" onClick={()=>setCamera(c=>({...c,zoom:Math.max(.55,c.zoom-.1)}))}><Minus size={15}/></button><span className="zoom-label">{Math.round(camera.zoom*100)}%</span><button className="square-tool" onClick={()=>setCamera(c=>({...c,zoom:Math.min(2.2,c.zoom+.1)}))}><Plus size={15}/></button><button className="square-tool" onClick={resetCamera} title="Recentralizar câmera"><LocateFixed size={15}/></button></>:<><button className="square-tool" onClick={()=>setZoom(Math.max(.8,zoom-.1))}><Minus size={15}/></button><span className="zoom-label">{Math.round(zoom*100)}%</span><button className="square-tool" onClick={()=>setZoom(Math.min(1.2,zoom+.1))}><Plus size={15}/></button><button className="square-tool" onClick={()=>{setZoom(1);pick('root')}} title="Recentralizar"><LocateFixed size={15}/></button></>}</div></div>
        {query&&<div className="search-results"><div className="result-head">{filtered.length} resultados</div>{filtered.map(n=><button key={n.id} onClick={()=>{pick(n.id);setQuery('')}}><Search size={14}/><span><strong>{n.title}</strong><small>{n.article}</small></span><ArrowUpRight size={14}/></button>)}</div>}
        <div className={`map-stage ${mode==='3D'?'interactive-3d':''} ${backFacing?'back-facing':''} ${focusedNode&&mode==='2D'?'focus-active':''}`} style={{'--map-scale':zoom,'--rot-x':`${camera.x}deg`,'--rot-y':`${camera.y}deg`,'--pan-x':`${camera.panX}px`,'--pan-y':`${camera.panY}px`,'--camera-zoom':camera.zoom,'--focus-x':`${focusOffset.x}px`,'--focus-y':`${focusOffset.y}px`,'--focus-scale':focusOffset.scale}} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp} onContextMenu={e=>{if(mode==='3D')e.preventDefault()}} onWheel={onWheel}><div className="map-world"><div className="map-grid"/><svg className="edges" viewBox="0 0 1000 700" preserveAspectRatio="none">{edges.filter(([a,b])=>visible(nodes.find(n=>n.id===a))&&visible(nodes.find(n=>n.id===b))).map(([a,b])=>{const na=nodes.find(n=>n.id===a),nb=nodes.find(n=>n.id===b);return <line key={a+b} x1={na.x*10} y1={na.y*7} x2={nb.x*10} y2={nb.y*7} className={`edge ${a==='comercializacao'||b==='comercializacao'?'edge-active':''}`}/>})}</svg>
          <div className="map-nodes">{nodes.filter(visible).map((n,i)=><button key={n.id} onClick={()=>pick(n.id)} onDoubleClick={e=>toggleNodeFocus(e,n)} title={focusedNode===n.id?'Clique duas vezes para voltar ao enquadramento':'Clique duas vezes para aproximar e focar'} className={`map-node ${n.kind} ${selected===n.id?'selected':''} ${focusedNode===n.id?'focused':''} ${persona!=='todos'&&((persona==='consumidor'&&n.env==='ACR')||(persona==='distribuidor'&&n.env==='ACL'))?'dimmed':''}`} style={{left:`${n.x}%`,top:`${n.y}%`,'--z':`${n.z}px`,'--delay':`${i*45}ms`}}><span className={`node-face-content ${backFacing?'back-content':''}`}>{backFacing?<span className="node-back-content"><span className="node-back-kicker">EM PROFUNDIDADE</span><strong>{n.title}</strong><small>{n.article}</small><span>{nodeInsights[n.id]}</span></span>:<><span className="node-icon">{n.kind==='timeline'?<Clock3 size={15}/>:n.kind==='quiz'?<Sparkles size={15}/>:n.id==='root'?<Network size={17}/>:<GitBranch size={15}/>}</span><span className="node-copy"><strong>{n.title}</strong><small>{n.short}</small></span>{n.id==='root'&&<span className="root-badge">NORMA</span>}</>}</span></button>)}</div>
          <div className="map-caption"><span className="caption-line"/> Relações entre temas <span className="caption-dot"/> {mode==='2D'?'Mapa topológico':'Profundidade hierárquica'}</div>
          </div>{mode==='3D'&&<><div className="view-cube"><button className="cube" onClick={resetCamera} title="Restaurar vista"><span>TOPO</span><i/><b/><em/></button><small>ARRASTE PARA ORBITAR</small></div><div className="interaction-hint"><Orbit size={13}/> Arrastar: orbitar <span>·</span> Shift + arrastar: mover <span>·</span> Scroll: zoom</div></>}
        </div>
        <div className="bottom-bar"><a className="course-link" href="https://academy.ccee.org.br/" target="_blank" rel="noopener noreferrer"><GraduationCap size={16}/><span><strong>Aprofunde o tema</strong><small>Academy CCEE</small></span><ArrowUpRight size={14}/></a><div className="bottom-crumb"><span>Decreto 5.163</span><span>›</span><strong>{current.title}</strong></div><button className="mini-map" onClick={()=>{setZoom(1);pick('root')}} title="Minimapa"><span className="mini-line l1"/><span className="mini-line l2"/><i/><b/></button></div>
      </section>
      {drawer&&<aside className="detail-panel"><div className="detail-top"><div><span className="section-label">DETALHE DO TEMA</span><button className="close-drawer" onClick={()=>setDrawer(false)}><PanelRightClose size={17}/></button></div><span className="category-chip"><i className={`layer-dot ${current.layer}`}/>{layerLabels[current.layer]}</span></div><div className="detail-content"><div className="detail-icon"><BookOpen size={19}/></div><h1>{current.title}</h1><p className="detail-subtitle">{current.short}</p><div className="article-ref"><span>REFERÊNCIA</span><strong>{current.article}</strong><button title="Abrir referência"><ArrowUpRight size={14}/></button></div><h3>Visão geral</h3><p className="summary">{current.summary}</p>{current.id==='leiloes'&&<div className="timeline"><span>A-5</span><i/><span>A-3</span><i/><span>A-1</span><small>Antecedência do início do fornecimento</small></div>}{current.id==='quiz'&&<div className="quiz-card"><strong>Qual perfil descreve você?</strong><button onClick={()=>setToast('Consulte os requisitos vigentes antes de tomar uma decisão.')}>Sou consumidor de energia <ArrowUpRight size={14}/></button><small>Esta trilha é educativa. Confira a regulamentação vigente.</small></div>}<button className="open-article" onClick={()=>setToast('Referência pronta para consulta no texto oficial.')}>Ver contexto no decreto <ArrowUpRight size={15}/></button><div className="related"><span>RELACIONADOS</span>{nodes.filter(n=>n.id!==current.id&&edges.some(e=>e.includes(current.id)&&e.includes(n.id))).slice(0,3).map(n=><button key={n.id} onClick={()=>pick(n.id)}>{n.title}<ArrowUpRight size={13}/></button>)}</div></div></aside>}
    </div>{toast&&<div className="toast"><span className="live-dot"/>{toast}<button onClick={()=>setToast('')}><X size={14}/></button></div>}
  </main>
}
